
build:
	## cloudformation custome resource plugins
	npm install
	cd build.f; node run_upload_code index_alertmessages

buildlambda: build
	# no more tasks

buildnpm:
	npm install;

clean:
	# nothing to do
